### PR TITLE
Auto-Discovery

### PR DESCRIPTION
**Pull request by buzzclue**

### CODE REVIEW

**Comment by sergiz** [comment]
https://github.com/JackieDo/Laravel-Dotenv-Editor/pull/26

**Comment by buzzclue** [comment]
You missed 'aliases'.. I hope it gets merged.

**Comment by sergiz** [comment]
I intentionally removed it recently. And this project appears very well dead.

**Comment by JackieDo** [comment]
> I intentionally removed it recently. And this project appears very well dead.

@sergiz : In the past time, I could not take care of the project due to bad health. Now I have come back and I guarantee this project will not die. Thanks for your pull request #26, but I decided to merge this pull request.

**Pull request merged**
