### PR TITLE
laravel 11 support

### PR DESCRIPTION
**Pull request by dev-mazur**

### CODE REVIEW

**Comment by dev-mazur** [comment]
@JackieDo

**Comment by AlexisSerneels** [comment]
@JackieDo Thank you.

**Comment by EvilBMP** [comment]
@JackieDo Any updates on this one? It's just a small fix for projects, that also require other Symfony v7 packages. Thanks!

**Comment by adamczykpiotr** [comment]
@JackieDo Please accept this PR

**Comment by Sm1g00l** [comment]
@JackieDo Please I needed this PR too!!

**Comment by akbardwi** [comment]
@JackieDo please accept this PR, i need too

**Comment by suhailparad** [comment]
any update on this ?

**Comment by EvilBMP** [comment]
Try my fork https://github.com/portrino/companienv

**Comment by andrefelipe18** [comment]
@JackieDo hey

**Pull request closed without merging**
